import { cn } from '@/lib/utils'
import './global.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import AuthProvider from '@/lib/AuthProvider'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'AIgnite | Quiz',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    // <AuthProvider>
    <html lang="en">
      <Navbar />
      <body className={cn(inter.className, "antialiased min-h-screen")}>{children}</body>
    </html>
    // </AuthProvider>
  )
}
